<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0ce6af1da62c466f78696fcc0e4cf502
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'Medoo\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Medoo\\' => 
        array (
            0 => '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0ce6af1da62c466f78696fcc0e4cf502::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0ce6af1da62c466f78696fcc0e4cf502::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
